---
version: "3"

tasks:
  watch:css:
    cmds:
      - ./tailwindcss -i ./templates/tailwind.css -o ./build/styles.css --watch --minify

  watch:go:
    cmds:
      - air

  watch:templ:
    cmds:
      - templ generate --proxy="http://localhost:5500/build" --watch --open-browser=false
